config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 root to: 'homes#top'
 get "home/about" => "homes#about"


    resources :books

    resources :users, only: [:show, :edit, :index, :update]
  end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body,  presence: true, length: { maximum: 200 }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])

  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    @books = Book.all
    if @book.save
    redirect_to book_path(@book)
    flash[:notice] = "Book was successfully created"
    else
    render:'index'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path

  end

  def update
    @book = Book.find(params[:id])
  if  @book.update(book_params)
    redirect_to book_path(@book.id)
    flash[:notice] = "Book was successfully created"
  else
    render :edit
  end
  end

   private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    unless current_user.id == @book.user_id
    redirect_to books_path
    end
  end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <p><%= @book.errors.count %> errors prohibited this book from being saved:</p>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>

<h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>


  <%= f.submit 'Update Book' %>

<%= link_to "Show", book_path %>
  <%= link_to "Back", books_path %>



  <% end %>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container">
  <div class="row">

<%= render 'users/info', user: @user,book: @book %>

<div class="col-md-8 offset-md-1">


<h1>Books</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>opinion</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user) do %>
        <%= attachment_image_tag book.user, :profile_image,fallback: "no_image.jpg" %>
        <% end %>
      </td>
      <td><%= link_to "#{book.title}", book_path(book)  %></td>
      <td><%=  book.body  %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<did/>
    <did/>
    <did/>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container">
  <div class="row">

<%= render 'users/info', user: @user, book: @book_new %>

<div class="col-md-8 offset-md-1">

<h1>Book detail</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
      <%= link_to user_path(@book.user) do %>
      <%= attachment_image_tag @book.user, :profile_image,fallback: "no_image.jpg" %>
      <%=  @book.user.name  %>
      <% end %>
      </td>
      <td><%=  @book.title  %></td>
      <td><%=  @book.body  %></td>

      <% if user_signed_in? && current_user.id == @book.user_id %>
      <td><%= link_to "Edit", edit_book_path(@book) %></td>
      <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
      <% end %>

    </tr>
</tbody>
</table>

<did/>
    <did/>
    <did/>