config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 root to: 'homes#top'
 get "home/about" => "homes#about"


    resources :books

    resources :users, only: [:show, :edit, :index, :update]
  end

app/views/layouts/_base.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: key) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <title>Bookers2App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", root_path %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>


    <li>
        <i class="fas fa-home text-light"></i>
      <%= link_to 'Home', user_path(current_user.id) %>
    </li>
      <li>
        <i class="fas fa-users text-light"></i>
        <%= link_to "Users", users_path %>
      </li>

      <li>
        <i class="fas fa-book-open text-light"></i>
        <%= link_to "Books", books_path %>
      </li>

      <li>
        <i class="fas fa-sign-out-alt text-light"></i>
        <%= link_to "logout", destroy_user_session_path, method: :delete %>
      </li>


    <% else %>
      <li>
        <i class="fas fa-home text-light"></i>
        <%= link_to "Home", root_path %>
      </li>

      <li>
        <i class="fas fa-link text-light"></i>
        <%= link_to "about", home_about_path %>
      </li>

      <li>
        <i class="fas fa-user-plus text-light"></i>
        <%= link_to "sign up", new_user_registration_path %>
      </li>
      <li>
        <i class="fas fa-sign-in-alt text-light"></i>
        <%= link_to "login", new_user_session_path %>
      </li>

    <% end %>
    </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= render 'layouts/base' %>


    <%= yield %>
  </body>
</html>